name: QuarkusApp

services:
  rabbitmq:
    image: rabbitmq:4.3.6-management
    container_name: quarkus-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - quarkus-net
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:18.6
    container_name: quarkus-postgres
    environment:
      POSTGRES_DB: quarkus_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
#      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/changelog/baseline/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quarkus-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3

  quarkus-app:
    build:
      dockerfile: src/main/docker/Dockerfile.jvm
    container_name: quarkus-app
    restart: always
    ports:
      - 8080:8080
    networks:
      - quarkus-net
    depends_on:
      - rabbitmq
      - postgres


networks:
  quarkus-net:
    driver: bridge
