name: QuarkusApp

services:
  rabbitmq:
    image: rabbitmq:4.3.6-management
    container_name: quarkus-rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=rmuser
      - RABBITMQ_DEFAULT_PASS=rmpassword
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}] disk_free_limit 2147483648
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - quarkus-net
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics check_port_connectivity" ]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 60s

  postgres:
    image: postgres:18.6
    container_name: quarkus-postgres
    environment:
      POSTGRES_DB: quarkus_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    volumes:
#      - postgres_data:/var/lib/postgresql/data
      - ./src/main/resources/db/changelog/baseline/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - quarkus-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  quarkus-app:
    build:
      # Для JVM образа
      #      dockerfile: src/main/docker/Dockerfile.jvm
      #    image: quarkusapp:latest
      #    container_name: quarkus-app
      #
      # Для Native образа
      dockerfile: src/main/docker/Dockerfile.native
    image: quarkusapp-native:latest
    container_name: quarkus-app-native
    #
    restart: always
    ports:
      - 8080:8080
    networks:
      - quarkus-net
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      # Для RabbitMQ
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      RABBITMQ_USERNAME: rmuser
      RABBITMQ_PASSWORD: rmpassword
      # Для PostgreSQL
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/quarkus_db
      QUARKUS_DATASOURCE_USERNAME: postgres
      QUARKUS_DATASOURCE_PASSWORD: postgres


networks:
  quarkus-net:
    driver: bridge
