# --- Логирование ---
quarkus.log.level=INFO
#quarkus.log.file.enable=true
#quarkus.log.file.path=logs/app.log
#quarkus.log.file.encoding=UTF-8
#quarkus.log.file.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c] %s%n

# Ротация по дате — каждый день новый файл
#quarkus.log.file.rotation.max-backup-index=7
#quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd
#quarkus.log.file.rotation.rotate-on-boot=true
# --- DataSource ---
%dev.quarkus.datasource.devservices.enabled=false
%dev.quarkus.datasource.db-kind=postgresql
%dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_db
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=postgres
quarkus.datasource.devservices.image-name=postgres:18.6
# --- Hibernate ---
quarkus.hibernate-orm.validate-in-dev-mode=false
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.database.default-schema=quarkus_app
# --- Liquibase ---
quarkus.liquibase.migrate-at-start=true
quarkus.liquibase.contexts=*
quarkus.liquibase.change-log=db/changelog/changelog-master.xml
quarkus.liquibase.default-schema-name=quarkus_app
quarkus.liquibase.enabled=true
# --- RabbitMQ ---
%dev.quarkus.rabbitmq.devservices.enabled=false
%dev.rabbitmq-host=localhost
%dev.rabbitmq-port=5672
%dev.rabbitmq-username=rmuser
%dev.rabbitmq-password=rmpassword
quarkus.rabbitmq.devservices.image-name=rabbitmq:4.3.6-management

# Входящий канал (consumer)
mp.messaging.incoming.order-events-create.connector=smallrye-rabbitmq
mp.messaging.incoming.order-events-create.declare=true
mp.messaging.incoming.order-events-create.queue.name=order-events
mp.messaging.incoming.order-events-create.queue.routing-keys=order.create
mp.messaging.incoming.order-events-create.exchange.name=orders-exchange

# Исходящий канал (producer)
mp.messaging.outgoing.order-events-created.connector=smallrye-rabbitmq
mp.messaging.outgoing.order-events-created.declare=true
mp.messaging.outgoing.order-events-created.default-routing-key=order.created
mp.messaging.outgoing.order-events-created.exchange.name=orders-exchange