#PostgreSQL Configuration
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_db
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.devservices.enabled=false

#Liquibase Configuration
quarkus.liquibase.change-log=src/main/resources/db/changelog/changelog-master.xml
quarkus.liquibase.default-schema-name=quarkus_app

#RabbitMQ Configuration
quarkus.rabbitmq.devservices.enabled=false