#PostgreSQL Configuration
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/quarkus_db
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.devservices.enabled=false

quarkus.hibernate-orm.enabled=false

#Liquibase Configuration
quarkus.liquibase.change-log=src/main/resources/db/changelog/changelog-master.xml
quarkus.liquibase.default-schema-name=quarkus_app
quarkus.liquibase.enabled=true

#RabbitMQ Configuration
quarkus.rabbitmq.devservices.enabled=false